src/section/FAQ/Faq.tsx(1,8): error TS6133: 'React' is declared but its value is never read. src/section/FAQ/Faq.tsx(26,19): error TS7006: Parameter 'index' implicitly has an 'any' type.